In [ ]:
import pandas as pd

# carregar dataset
df = pd.read_csv("../data/goodreads_books_dataset.csv")

In [11]:
df.head()

,id,title,series,description,pages,publicationDate,language,rating,ratings,imageURL,genres,amazonLink,ISBN,author,popularReviews
0,90202302,Iron Flame,"{'title': 'The Empyrean', 'self_position': '2'}",Everyone expected Violet Sorrengail to die dur...,640,2023-11-07,English,4.36,2502458,https://m.media-amazon.com/images/S/compressed...,"['Fantasy', 'Romance', 'Romantasy', 'Dragons',...",https://www.amazon.com/gp/product/B0C4JMJBNX/r...,9781649374172,"{'name': 'Rebecca Yarros', 'about': 'Rebecca Y...","[{'user': {'name': 'Angie', 'imageURL': 'https..."
1,209439446,Onyx Storm,"{'title': 'The Empyrean', 'self_position': '3'}",After nearly eighteen months at Basgiath War C...,544,2025-01-21,English,4.21,1565867,https://m.media-amazon.com/images/S/compressed...,"['Fantasy', 'Romantasy', 'Romance', 'Audiobook...",https://www.amazon.com/gp/product/B0CW1FKFB9/r...,9781649374189,"{'name': 'Rebecca Yarros', 'about': 'Rebecca Y...","[{'user': {'name': 'Clace ', 'imageURL': 'http..."
2,40045986,The Last Letter,NaN,"Beckett,\nIf you’re reading this, well, you kn...",426,2019-02-26,English,4.49,414025,https://m.media-amazon.com/images/S/compressed...,"['Romance', 'Fiction', 'Book Club', 'Contempor...",https://www.amazon.com/gp/product/B07FCF2GYW/r...,9781640635333,"{'name': 'Rebecca Yarros', 'about': 'Rebecca Y...",[{'user': {'name': 'Astrid - The Bookish Sweet...
3,53137938,The Things We Leave Unfinished,NaN,Twenty-eight-year-old Georgia Stanton has to s...,400,2021-02-23,English,4.31,409380,https://m.media-amazon.com/images/S/compressed...,"['Romance', 'Audiobook', 'Historical Fiction',...",https://www.amazon.com/gp/product/B087VXZYMM/r...,9781682815663,"{'name': 'Rebecca Yarros', 'about': 'Rebecca Y...","[{'user': {'name': 'jessica', 'imageURL': 'htt..."
4,127152907,In the Likely Event,NaN,"When Izzy Astor gets on a plane to go home, sh...",348,2023-08-01,English,4.21,248331,https://m.media-amazon.com/images/S/compressed...,"['Romance', 'Audiobook', 'Fiction', 'Contempor...",https://www.amazon.com/gp/product/B0BP8JRWLP/r...,9781662511561,"{'name': 'Rebecca Yarros', 'about': 'Rebecca Y...","[{'user': {'name': 'chan ☆', 'imageURL': 'http..."

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 947 entries, 0 to 946
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               947 non-null    int64
 1   title            947 non-null    object
 2   series           339 non-null    object
 3   description      896 non-null    object
 4   pages            947 non-null    int64
 5   publicationDate  907 non-null    object
 6   language         897 non-null    object
 7   rating           947 non-null    float64
 8   ratings          947 non-null    int64
 9   imageURL         891 non-null    object
 10  genres           947 non-null    object
 11  amazonLink       947 non-null    object
 12  ISBN             711 non-null    object
 13  author           947 non-null    object
 14  popularReviews   947 non-null    object
dtypes: float64(1), int64(3), object(11)
memory usage: 111.1+ KB

In [17]:
df[df['title'] == 'Untitled']

,id,title,series,description,pages,publicationDate,language,rating,ratings,imageURL,genres,amazonLink,ISBN,author,popularReviews
25,204802999,Untitled,"{'title': 'The Empyrean', 'self_position': '4'}",Rebecca Yarros has confirmed and stated on sev...,0,NaN,English,4.5,1079,NaN,"['Fantasy', 'Romantasy', 'Romance', 'Dragons',...",http://www.amazon.com/gp/product/B0FHMDXXTS/re...,NaN,"{'name': 'Rebecca Yarros', 'about': 'Rebecca Y...","[{'user': {'name': 'Katherine', 'imageURL': 'h..."
895,204802999,Untitled,"{'title': 'The Empyrean', 'self_position': '4'}",Rebecca Yarros has confirmed and stated on sev...,0,NaN,English,4.5,1079,NaN,"['Fantasy', 'Romantasy', 'Romance', 'Dragons',...",http://www.amazon.com/gp/product/B0FHMDXXTS/re...,NaN,"{'name': 'Rebecca Yarros', 'about': 'Rebecca Y...","[{'user': {'name': 'Katherine', 'imageURL': 'h..."

In [18]:
# remover colunas irrelevantes (ajusta conforme dataset)
df = df[['title', 'author', 'rating', 'description', 'genres', 'pages']]

# remover linhas sem descrição
df = df.dropna(subset=['description'])

# remover duplicados
df = df.drop_duplicates(subset=['title'])

# reset index
df = df.reset_index(drop=True)

print(df.shape)

(855, 6)

In [ ]:
df['content'] = df['title'] + " " + df['description']

In [ ]:
df.head()

In [ ]:
df.to_csv("../data/clean_books.csv", index=False)

In [ ]:
df_clean = pd.read_csv("../data/clean_books.csv")
df_clean.head()